### ISSUE TITLE
2nd disk mount is wrong

### ISSUE THREAD

**Issue by tuxmea** [betadots/foreman-training#4]
```
echo "\n/dev/sda2 /var/lib/pulp	xfs	defaults	1 1\n" >> /etc/fstab
mount -a
df

```
creates an fstab entry with no whitespaces.

**Comment by ngoralski** [comment]
Solution :
`echo -e "\n/dev/sda2 /var/lib/pulpxfs\tdefaults\t1\t1\n" >> /etc/fstab`
